[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
